version: "3"
services:
    angularapp:
        build:
            context: ./elyadata-blog-app
            dockerfile: angular-dockerfile-dev
        ports:
            - "${APP_UI_PORT}:4200"
    app:
        build: .
        depends_on:
            - postgres
        links:
            - postgres
        environment:
            DB_HOST: ${DB_HOST} 
            DB_USER: ${DB_USER} 
            DB_PASSWORD: ${DB_PASSWORD} 
            DB: ${DB} 
            PORT: ${DB_PORT} 
        ports:
            - "${APP_PORT}:3000" 
            - "9229:9229"

    postgres:
        image: postgres:12
        ports:
            - "35432:35432"
            - "${DB_PORT}:5432" 
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER} 
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
            POSTGRES_DB: ${POSTGRES_DB} 
            APP_DB_NAME: ${DB} 
            APP_DB_USER: ${DB_USER} 
            APP_DB_PASS: ${DB_PASSWORD} 
        volumes:
            - ${INIT_DB_LOCAL_PATH}:${INIT_DB_IMG_PATH}

